<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;
use App\Models\Service;
use App\Models\CityServiceContent;
use Illuminate\Support\Facades\DB;

class CustomerRegionServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('Starting Regional Service Assignment...');

        // 1. Load all 212 customer regions
        $cities = City::all();
        $cityCount = $cities->count();
        $this->command->info("Found {$cityCount} customer regions.");

        // 2. Load all global services
        $services = Service::all();
        $serviceCount = $services->count();
        $this->command->info("Found {$serviceCount} global services.");

        $expectedTotal = $cityCount * $serviceCount;
        $this->command->info("Target relationship count: {$expectedTotal}");

        $created = 0;
        $updated = 0;
        $skipped = 0;

        DB::beginTransaction();
        try {
            foreach ($cities as $city) {
                foreach ($services as $service) {
                    // Use firstOrCreate or updateOrCreate to remain idempotent
                    // We ensure that the service is associated with the city.
                    $record = CityServiceContent::firstOrCreate(
                        [
                            'city_id'    => $city->id,
                            'service_id' => $service->id,
                        ],
                        [
                            'category' => $service->category,
                            // Other SEO fields remain null for now as they'll be generated by AI later
                        ]
                    );

                    if ($record->wasRecentlyCreated) {
                        $created++;
                    } else {
                        $skipped++;
                    }
                }
            }
            DB::commit();
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error("Error during seeding: " . $e->getMessage());
            return;
        }

        $this->command->info("Seeding complete.");
        $this->command->info("Newly created: {$created}");
        $this->command->info("Already existed (skipped): {$skipped}");
        $this->command->info("Total relationships now: " . CityServiceContent::count());
    }
}
