<?php
/**
 * Fetch district counts for VERIFIED cities using Wilayah.id API.
 * Reads mapping_summary_v3.json generated by the mapping script.
 * Outputs wilayah_district_counts.json with per-regency district counts and total.
 */

function fetchJson($url) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    $data = curl_exec($ch);
    if (curl_errno($ch)) {
        fwrite(STDERR, "cURL error: " . curl_error($ch) . "\n");
        exit(1);
    }
    $code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);
    if ($code !== 200) {
        fwrite(STDERR, "HTTP $code fetching $url\n");
        exit(1);
    }
    return json_decode($data, true);
}

$summaryPath = __DIR__ . '/mapping_summary_v3.json';
if (!file_exists($summaryPath)) {
    fwrite(STDERR, "Mapping summary file not found: $summaryPath\n");
    exit(1);
}

$summaryData = json_decode(file_get_contents($summaryPath), true);
if ($summaryData === null) {
    fwrite(STDERR, "Failed to parse mapping_summary_v3.json\n");
    exit(1);
}

$verifiedCodes = [];
foreach ($summaryData['details'] as $city) {
    $classification = $city['classification'] ?? '';
    if (strpos($classification, 'VERIFIED') === 0) {
        if (!empty($city['matches'])) {
            foreach ($city['matches'] as $match) {
                $code = $match['code'];
                $name = $match['name'];
                $verifiedCodes[$code] = $name; // deduplicate by code
            }
        }
    }
}

$results = [];
$totalDistricts = 0;
foreach ($verifiedCodes as $code => $regencyName) {
    $url = "https://wilayah.id/api/districts/{$code}.json";
    $districtData = fetchJson($url);
    // Wilayah.id returns { "data": [ {"code":..., "name":...}, ... ] }
    $districts = $districtData['data'] ?? [];
    $count = count($districts);
    $totalDistricts += $count;
    $results[$code] = [
        'regency_name' => $regencyName,
        'district_count' => $count,
        'districts' => $districts,
    ];
    echo "Fetched {$count} districts for {$regencyName} ({$code}) via Wilayah.id\n";
}

$output = [
    'total_verified_cities' => count($verifiedCodes),
    'total_districts' => $totalDistricts,
    'details' => $results,
];

file_put_contents('wilayah_district_counts.json', json_encode($output, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE));

echo "Wilayah.id district counts written to wilayah_district_counts.json\n";
?>