<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Add BPS code to cities table
        Schema::table('cities', function (Blueprint $table) {
            $table->string('bps_code')->nullable()->unique()->after('slug');
        });

        // Add BPS code to kecamatans table
        Schema::table('kecamatans', function (Blueprint $table) {
            $table->string('bps_code')->nullable()->after('status');
            // Composite unique index on city_id + bps_code (allows multiple NULLs)
            $table->unique(['city_id', 'bps_code']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('cities', function (Blueprint $table) {
            // Drop the unique index on bps_code (generated by Laravel)
            $table->dropUnique(['bps_code']);
            $table->dropColumn('bps_code');
        });

        Schema::table('kecamatans', function (Blueprint $table) {
            // Drop the composite unique index on city_id + bps_code
            $table->dropUnique(['city_id', 'bps_code']);
            $table->dropColumn('bps_code');
        });
    }
};
